global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "api-gateway-local"
    static_configs:
      - targets: ["host.docker.internal:8000"]
    metrics_path: /metrics

  - job_name: "business-service-local"
    static_configs:
      - targets: ["host.docker.internal:8001"]
    metrics_path: /metrics

  - job_name: "recommendation-service-local"
    static_configs:
      - targets: ["host.docker.internal:8002"]
    metrics_path: /metrics

  - job_name: "ingestion-service-local"
    static_configs:
      - targets: ["host.docker.internal:8003"]
    metrics_path: /metrics
