# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x04yelp\"\xa0\x01\n\rReviewMessage\x12\x11\n\treview_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x13\n\x0b\x62usiness_id\x18\x03 \x01(\t\x12\r\n\x05stars\x18\x04 \x01(\x02\x12\x0e\n\x06useful\x18\x05 \x01(\x05\x12\r\n\x05\x66unny\x18\x06 \x01(\x05\x12\x0c\n\x04\x63ool\x18\x07 \x01(\x05\x12\x0c\n\x04text\x18\x08 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\t \x01(\t\"~\n\x0bUserMessage\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0creview_count\x18\x03 \x01(\x05\x12\x15\n\ryelping_since\x18\x04 \x01(\t\x12\x0c\n\x04\x66\x61ns\x18\x05 \x01(\x05\x12\x15\n\raverage_stars\x18\x06 \x01(\x02\"h\n\nTipMessage\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x13\n\x0b\x62usiness_id\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\x18\n\x10\x63ompliment_count\x18\x05 \x01(\x05\"3\n\x0e\x43heckinMessage\x12\x13\n\x0b\x62usiness_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REVIEWMESSAGE']._serialized_start=23
  _globals['_REVIEWMESSAGE']._serialized_end=183
  _globals['_USERMESSAGE']._serialized_start=185
  _globals['_USERMESSAGE']._serialized_end=311
  _globals['_TIPMESSAGE']._serialized_start=313
  _globals['_TIPMESSAGE']._serialized_end=417
  _globals['_CHECKINMESSAGE']._serialized_start=419
  _globals['_CHECKINMESSAGE']._serialized_end=470
# @@protoc_insertion_point(module_scope)
